# Generated by Django 4.1.3 on 2022-11-23 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FailureNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory_number_machine', models.CharField(max_length=128, unique=True)),
                ('factory_number_engine', models.CharField(max_length=128)),
                ('factory_number_transmission', models.CharField(max_length=128)),
                ('factory_number_drive_axle', models.CharField(max_length=128)),
                ('factory_number_steering_bridge', models.CharField(max_length=128)),
                ('supply_contract', models.CharField(max_length=128)),
                ('date_of_shipment', models.DateField()),
                ('consumer', models.CharField(max_length=128)),
                ('delivery_address', models.CharField(max_length=128)),
                ('equipment', models.CharField(max_length=128)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ModelsDriveAxle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ModelsEngine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ModelsMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ModelsSteeringBridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ModelsTransmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='RecoveryMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='TypeMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_maintenance', models.DateField()),
                ('operating_time', models.PositiveIntegerField()),
                ('work_order', models.CharField(max_length=128)),
                ('date_work_order', models.DateField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Backend.machine')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Backend.servicecompany')),
                ('type_maintenance', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Backend.typemaintenance')),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='model_transmission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Backend.modelstransmission'),
        ),
        migrations.AddField(
            model_name='machine',
            name='models_drive_axle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Backend.modelsdriveaxle'),
        ),
        migrations.AddField(
            model_name='machine',
            name='models_engine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Backend.modelsengine'),
        ),
        migrations.AddField(
            model_name='machine',
            name='models_machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Backend.modelsmachine'),
        ),
        migrations.AddField(
            model_name='machine',
            name='models_steering_bridge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Backend.modelssteeringbridge'),
        ),
        migrations.AddField(
            model_name='machine',
            name='service_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Backend.servicecompany'),
        ),
        migrations.CreateModel(
            name='Claims',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_rejection', models.DateField()),
                ('operating_time', models.PositiveIntegerField()),
                ('description_failure', models.CharField(max_length=128)),
                ('used_spare_parts', models.CharField(max_length=512)),
                ('date_recovery', models.DateField()),
                ('machine_downtime', models.PositiveIntegerField()),
                ('failure_node', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Backend.failurenode')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Backend.machine')),
                ('recovery_method', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Backend.recoverymethod')),
                ('service_company', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Backend.servicecompany')),
            ],
        ),
    ]
