# Generated by Django 4.1.3 on 2022-11-27 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.CharField(help_text='Описание (только для Клиента и Сервисной компании)', max_length=512, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(help_text='Название (только для Клиента и Сервисной компании)', max_length=128, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CL', 'Client'), ('SC', 'Service company'), ('MN', 'Manager')], default='CL', max_length=2, verbose_name='Роль'),
        ),
    ]
