# Generated by Django 4.1.3 on 2022-11-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_alter_user_description_alter_user_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.CharField(blank=True, help_text='Описание (только для Клиента и Сервисной компании)', max_length=512, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, help_text='Название (только для Клиента и Сервисной компании)', max_length=128, null=True, verbose_name='Название'),
        ),
    ]
