# Generated by Django 4.1.3 on 2022-11-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_alter_claims_options_alter_failurenode_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claims',
            name='machine_downtime',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
