# Generated by Django 4.1.3 on 2022-11-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_alter_claims_machine_downtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='equipment',
            field=models.CharField(max_length=512),
        ),
    ]
