# Generated by Django 4.1.3 on 2022-11-25 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_alter_machine_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claims',
            name='service_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Backend.servicecompany'),
        ),
    ]
