# Generated by Django 4.1.3 on 2022-11-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0005_alter_claims_service_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='factory_number_machine',
            field=models.CharField(max_length=128, unique=True, verbose_name='Заводской номер машины'),
        ),
    ]
