machine = [
    {
        "models_machine": "ПД1,5",
        "factory_number_machine": "0017",
        "models_engine": "Kubota D1803",
        "factory_number_engine": "7ML1035",
        "model_transmission": "10VA-00105",
        "factory_number_transmission": "21D0108251",
        "models_drive_axle": "20VA-00101",
        "factory_number_drive_axle": "21D0107997",
        "models_steering_bridge": "VS20-00001",
        "factory_number_steering_bridge": "21D0093265",
        "date_of_shipment": "2022-09-03",
        "client": 'ИП Трудников С.В.',
        "consumer": 'ИП Трудников С.В.',
        'delivery_address': 'п. Знаменский, Респ. Марий Эл',
        'equipment': '1. Гидролинии с БРС; 2. Дополнительеная установка кабины',
        'service_company': 'ООО Промышленная техника',
    },
    {
        "models_machine": "ПД5,0",
        "factory_number_machine": "0021",
        "models_engine": "ММЗ Д-243",
        "factory_number_engine": "112890",
        "model_transmission": "HF50-VP020",
        "factory_number_transmission": "20H0066",
        "models_drive_axle": "HA50-VP010",
        "factory_number_drive_axle": "20H0039",
        "models_steering_bridge": "B350655A",
        "factory_number_steering_bridge": "KDBAC9685",
        "date_of_shipment": "2022-01-14",
        "client": 'ООО "ФПК21"',
        "consumer": 'ООО "ДЭТ №13"',
        'delivery_address': 'с. Акуловка, Московская обл.',
        'equipment': 'Стандарт',
        'service_company': 'ООО Силант',
    },
    {
        "models_machine": "ПД5,0",
        "factory_number_machine": "0027",
        "models_engine": "ММЗ Д-243",
        "factory_number_engine": "167733",
        "model_transmission": "HF50-VP020",
        "factory_number_transmission": "20H0070",
        "models_drive_axle": "HA50-VP010",
        "factory_number_drive_axle": "20H0049",
        "models_steering_bridge": "B350655A",
        "factory_number_steering_bridge": "KDBAH6583",
        "date_of_shipment": "2022-04-28",
        "client": 'ООО "МНС77"',
        "consumer": 'ООО "Мосгоррест"',
        'delivery_address': 'г. Санкт-Петербург',
        'equipment': '1. Кабина с отопителем',
        'service_company': 'ООО Промышленная техника',
    },
    {
        "models_machine": "ПД3,0",
        "factory_number_machine": "0032",
        "models_engine": "Kubota V3300",
        "factory_number_engine": "2MU2983",
        "model_transmission": "10VB-00106",
        "factory_number_transmission": "21K0116785",
        "models_drive_axle": "20VB-00102",
        "factory_number_drive_axle": "21K0115910",
        "models_steering_bridge": "VS30-00001",
        "factory_number_steering_bridge": "00070422",
        "date_of_shipment": "2022-05-27",
        "client": 'ООО "ФПК21"',
        "consumer": 'ФРП России',
        'delivery_address': 'г. Челябинск, в/ч ',
        'equipment': '1. Кабина с отопителем; '
                     '2. Медицинская аптечка; '
                     '3. Проблесковый маячок; '
                     '4. Знак аварийной остановки; '
                     '5. Огнетушитель порошковый 5п;',
        'service_company': 'ООО Промышленная техника',
    },
    {
        "models_machine": "ПД3,0",
        "factory_number_machine": "0003",
        "models_engine": "Kubota V3300",
        "factory_number_engine": "2ME0639",
        "model_transmission": "10VB-00106",
        "factory_number_transmission": "21D0108264",
        "models_drive_axle": "20VB-00102",
        "factory_number_drive_axle": "21D0107988",
        "models_steering_bridge": "VS30-00001",
        "factory_number_steering_bridge": "0821004",
        "date_of_shipment": "2021-09-30",
        "client": 'ООО "Ранский ЛПХ"',
        "consumer": 'ООО "Ранский ЛПХ"',
        'delivery_address': 'п. Опарино, Кировская обл.',
        'equipment': 'Стандарт',
        'service_company': 'ООО Силант',
    },
    {
        "models_machine": "ПГ1,5",
        "factory_number_machine": "0016",
        "models_engine": "Nissan K21",
        "factory_number_engine": "049827",
        "model_transmission": "10VA-00105",
        "factory_number_transmission": "21D0108256",
        "models_drive_axle": "20VA-00101",
        "factory_number_drive_axle": "21D0108000",
        "models_steering_bridge": "VS20-00001",
        "factory_number_steering_bridge": "21D0093244",
        "date_of_shipment": "2021-12-20",
        "client": 'ООО "Комплект-Поставка"',
        "consumer": 'ООО "ГП СПБ"',
        'delivery_address': 'г. Санкт-Петербург',
        'equipment': '1. Кабина с отопителем; '
                     '2. Каретка смещения + гидролинии;',
        'service_company': 'ООО Промышленная техника',
    },
    {
        "models_machine": "ПД2,0",
        "factory_number_machine": "0039",
        "models_engine": "MMZ-4D",
        "factory_number_engine": "0015",
        "model_transmission": "HF30-VP010",
        "factory_number_transmission": "22B0001",
        "models_drive_axle": "HA30-02020",
        "factory_number_drive_axle": "22B3364",
        "models_steering_bridge": "VS20-00001",
        "factory_number_steering_bridge": "00010622",
        "date_of_shipment": "2022-07-18",
        "client": 'ООО "РМК"',
        "consumer": 'ФСН России',
        'delivery_address': 'г. Москва',
        'equipment': '1. Высота подъёма вил - 4 500мм;'
                     '2. Кабина с отопителем;'
                     '3. Шины суперэластик;'
                     '4. Прибор комбинированный КД8235;',
        'service_company': 'ООО Промышленная техника',
    },
    {
        "models_machine": "ПД2,5",
        "factory_number_machine": "0045",
        "models_engine": "MMZ-4D",
        "factory_number_engine": "000003",
        "model_transmission": "HF30-VP010",
        "factory_number_transmission": "22B0008",
        "models_drive_axle": "HA30-02020",
        "factory_number_drive_axle": "22B3370",
        "models_steering_bridge": "VS20-00001",
        "factory_number_steering_bridge": "00200622",
        "date_of_shipment": "2022-08-30",
        "client": 'АО "Зандер"',
        "consumer": 'АО Зандер',
        'delivery_address': 'г. Краснодар',
        'equipment': '1. Кабина с отопителем;'
                     '2. Каретка бокового смещения 1050мм;'
                     '3. Блокировка реверса хода;'
                     '4. Высота подъёма вил - 4800мм;'
                     '5. Прибор комбинированный КД8235;',
        'service_company': 'ООО Промышленная техника',
    },
    {
        "models_machine": "ПД5,0",
        "factory_number_machine": "0019",
        "models_engine": "ММЗ Д-243",
        "factory_number_engine": "112893",
        "model_transmission": "HF50-VP020",
        "factory_number_transmission": "20H0069",
        "models_drive_axle": "HA50-VP010",
        "factory_number_drive_axle": "20H0041",
        "models_steering_bridge": "B350655A",
        "factory_number_steering_bridge": "KDBAC9687",
        "date_of_shipment": "2022-01-28",
        "client": 'ООО "ФПК21"',
        "consumer": 'АО "Т-Минус"',
        'delivery_address': 'г. Первоуральск, Свердловской обл.',
        'equipment': '1. Высота подъёма вил - 4 500мм;'
                     '2. Центральный цилиндр подъёма ;'
                     '3. Кабина с отопителем;'
                     '4. Стрела безблочная Г-образная;',
        'service_company': 'ООО ФНС',
    },
    {
        "models_machine": "ПД3,0",
        "factory_number_machine": "0008",
        "models_engine": "Kubota V3300",
        "factory_number_engine": "2ME0753",
        "model_transmission": "10VB-00106",
        "factory_number_transmission": "21D0108269",
        "models_drive_axle": "20VB-00102",
        "factory_number_drive_axle": "21D0108011",
        "models_steering_bridge": "VS30-00001",
        "factory_number_steering_bridge": "0821005",
        "date_of_shipment": "2021-09-30",
        "client": 'ООО "Комплект-Поставка"',
        "consumer": 'ООО "ГП Краснодар"',
        'delivery_address': 'г. Краснодар',
        'equipment': '1. Кабина с отопителем;',
        'service_company': 'ООО ФНС',
    },
]
